---

- name: OpenVPN installation and clients keys generation
  hosts: all
  become: yes

  vars:
    openvpn_url: 52.47.178.92
    openvpn_pki_password: 29mTcV7zfMY394Ju6pVv2pFjzjhZBXGY
    # openvpn_dns: 169.254.169.253
    openvpn_dns: 172.40.0.2
    openvpn_routes:
      - route 172.40.0.0 255.255.0.0
      - route 172.40.0.0 255.255.255.0
    openvpn_clients:
      - ebarault

  tasks:
    - name: Call ovenvpn role with vars
      include_role:
         name: openvpn
      vars:
        url: "{{openvpn_url}}"
        pki_password: "{{openvpn_pki_password}}"
        dns: "{{openvpn_dns}}"
        routes: "{{openvpn_routes}}"
        clients: "{{openvpn_clients}}"
