---

- name: OpenVPN installation and clients keys generation
  hosts: all
  become: yes

  vars:
    openvpn_domain: {{ansible_domain}}
    openvpn_pki_password: 29mTcV7zfMY394Ju6pVv2pFjzjhZBXGY
    openvpn_clients:
        - ebarault

  tasks:
  - include_role:
       name: openvpn
    vars:
      domain: {{openvpn_domain}}
      pki_password: {{openvpn_pki_password}}
      clients: {{openvpn_clients}}
