---

- name: OpenVPN installation and clients keys generation
  hosts: all
  become: yes

  vars:
    openvpn_domain: 52.47.178.92
    openvpn_pki_password: 29mTcV7zfMY394Ju6pVv2pFjzjhZBXGY
    # openvpn_dns: 169.254.169.253
    openvpn_dns: 172.40.0.2
    openvpn_clients:
        - ebarault

  tasks:
  - include_role:
       name: openvpn
    vars:
      domain: "{{openvpn_domain}}"
      pki_password: "{{openvpn_pki_password}}"
      dns: "{{openvpn_dns}}"
      clients: "{{openvpn_clients}}"
